# Generated by Django 5.0.3 on 2024-04-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notesManage", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
